# Generated by Django 3.2.13 on 2023-06-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bamchat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_picture',
            field=models.ImageField(default='', upload_to='group_picture/'),
        ),
        migrations.AddField(
            model_name='post',
            name='post_img',
            field=models.ImageField(default='', upload_to='post_image/'),
        ),
    ]
